/**
 * Contract B — /api/chat streaming route.
 *
 * Receives: POST { messages: CoreMessage[] }
 * Returns:  a streaming AI SDK data-stream response (compatible with useChat).
 *
 * The model and provider are selected via getLanguageModel() in src/lib/config.ts.
 * The API key lives ONLY in server env vars — it is never sent to the client.
 *
 * export const runtime = 'nodejs' is required when using Ollama (native HTTP) so
 * Next.js does not try to run this in the Edge runtime.
 */

import { streamText } from "ai";
import type { ModelMessage } from "@ai-sdk/provider-utils";
import { getLanguageModel } from "@/lib/config";
import guideData from "@/data/guide.json";
import type { Guide } from "@/lib/guide";

export const runtime = "nodejs";

/** Serialize the full guide as a JSON block for the system prompt. */
const guide = guideData as Guide;
const guideBlock = JSON.stringify(guide, null, 2);

/**
 * PLACEHOLDER system prompt — the bot-engine agent will replace this with the
 * real persona/grounding prompt. Do NOT edit this file for persona changes;
 * update the system prompt string once the bot-engine task runs.
 */
const SYSTEM_PROMPT = `\
You are a friendly, concise local host concierge for the property at ${guide.property.address} \
in ${guide.property.neighborhood}.

Your ONLY knowledge source is the guide below. Answer questions about the property, WiFi, \
check-in/check-out, and the nearby places listed. If a question is about something not in the \
guide or unrelated to the property and its surroundings, warmly decline and redirect the guest \
to what you CAN help with.

Never invent place names, hours, prices, or facts not present in the guide. \
Be warm, brief, and practical — guests are on their phones.

GUIDE DATA (your only allowed knowledge source):
\`\`\`json
${guideBlock}
\`\`\`
`;

export async function POST(req: Request): Promise<Response> {
  const body = (await req.json()) as { messages: ModelMessage[] };
  const { messages } = body;

  const result = streamText({
    model: getLanguageModel(),
    system: SYSTEM_PROMPT,
    messages,
  });

  // AI SDK v6: use toTextStreamResponse() — toDataStreamResponse was removed in v6.
  return result.toTextStreamResponse();
}
